# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPE53ModificarCuenta():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_pE53ModificarCuenta(self):
    self.driver.get("http://127.0.0.1:5000/")
    self.driver.set_window_size(893, 681)
    self.driver.find_element(By.LINK_TEXT, "Your profile").click()
    self.driver.find_element(By.LINK_TEXT, "Edit Profile").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.NAME, "address1").click()
    self.driver.find_element(By.NAME, "address1").click()
    self.driver.find_element(By.NAME, "address1").send_keys("Independencia889")
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    dire = self.driver.find_element(By.NAME, "address1").text
    assert "Independencia 889" in dire

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.NAME, "address1").send_keys("Chile665")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #dire = self.driver.find_element(By.NAME, "address1").text
    #assert "Chile665" in dire

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.NAME, "address1").send_keys("Lima124")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #dire = self.driver.find_element(By.NAME, "address1").text
    #assert "Lima124" in dire

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(4)").click()
    self.driver.find_element(By.NAME, "address1").send_keys("line1")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "html")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.NAME, "email").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(10)").click()
    self.driver.find_element(By.NAME, "phone").send_keys("78945")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #tel = self.driver.find_element(By.NAME, "phone").text
    #assert "78945" in tel

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(10)").click()
    self.driver.find_element(By.NAME, "phone").send_keys("236589")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #tel = self.driver.find_element(By.NAME, "phone").text
    #assert "236589" in tel

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(10)").click()
    self.driver.find_element(By.NAME, "phone").send_keys("1234567989")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    #tel = self.driver.find_element(By.NAME, "phone").text
    #assert "1234567989" in tel

    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(10)").click()
    self.driver.find_element(By.NAME, "phone").send_keys("1234")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(11)").click()

    tel = self.driver.find_element(By.NAME, "phone").text
    assert "1234" in tel

    self.driver.find_element(By.LINK_TEXT, "Your profile").click()
    self.driver.find_element(By.LINK_TEXT, "Change password").click()
    self.driver.find_element(By.NAME, "oldpassword").click()
    self.driver.find_element(By.NAME, "oldpassword").send_keys("sample")
    self.driver.find_element(By.ID, "newpassword").click()
    self.driver.find_element(By.ID, "newpassword").send_keys("abc!=123")
    self.driver.find_element(By.ID, "cpassword").click()
    self.driver.find_element(By.ID, "cpassword").send_keys("abc!=123")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.NAME, "oldpassword").click()
    self.driver.find_element(By.NAME, "oldpassword").send_keys("abc!=123")
    self.driver.find_element(By.ID, "newpassword").click()
    self.driver.find_element(By.ID, "newpassword").send_keys("ghi_765")
    self.driver.find_element(By.CSS_SELECTOR, "form").click()
    self.driver.find_element(By.ID, "cpassword").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3)").click()
    self.driver.find_element(By.ID, "cpassword").send_keys("ghi_765")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.NAME, "oldpassword").click()
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(1)").click()
    self.driver.find_element(By.NAME, "oldpassword").send_keys("ghi_765")
    self.driver.find_element(By.ID, "newpassword").click()
    self.driver.find_element(By.ID, "newpassword").send_keys("sample")
    self.driver.find_element(By.ID, "cpassword").click()
    self.driver.find_element(By.ID, "cpassword").send_keys("sample")
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Go to Profile").click()
    self.driver.find_element(By.ID, "searchBox").click()
    self.driver.find_element(By.ID, "searchBox").send_keys("dress")
    self.driver.find_element(By.ID, "searchButton").click()
  
